# Generated by Django 5.0.6 on 2024-12-16 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El short_url solo puede contener letras y números.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
